INSERT INTO `question`
VALUES (1, 'Peru', 'Boliwia', 'Argentyna', 'Chile', 'A', 1, 'W którym państwie znajduje się Lima?'),
       (2, 'Buhaj', 'Cap', 'Warchlak', 'Odyniec', 'D', 2, 'Samiec dzika to:'),
       (3, 'hyżym', 'pstrym', 'łysym', 'gniadym', 'B', 3,
        'Uzupełnij staropolskie powiedzenie: Łaska pańska na ______ koniu jeździ'),
       (4, 'Posejdon', 'Narcyz', 'Atlas', 'Zeus', 'C', 4, 'Kto w mitologii greckiej dźwigał Ziemię na swoich barkach?'),
       (5, 'Arktyka', 'Antarktyka', 'Antarktyda', 'Atlantyda', 'A', 5, 'Obszar Ziemi otaczający biegun północny to:'),
       (6, 'Cheiloskopia', 'Daktyloskopia', 'Fonoskopia', 'Termoskopia', 'B', 6,
        'Technika śledcza zajmujca się badaniami porównawczymi linii papilarnych dłoni w celu ustalenia sprawcy czynu zabronionego to:'),
       (7, 'Repartimiento', 'Krucjaty', 'Konkwista', 'Korrida', 'C', 7,
        'Hiszpańskie wyprawy zbrojne podejmowane od końca XV wieku w celu podboju nowo odkrytych terytoriów zamorskich w Amerykach, Afryce i Indiach to:'),
       (8, 'Eric Clapton', 'David Bowie', 'Michael Jackson', 'Kurt Cobain', 'B', 8,
        'Kto wraz z Freddim Mercurym i zespołem Queen nagrał w 1981 r. piosenkę Under Pressure?'),
       (9, 'Płuc', 'Serca', 'Mózgu', 'Nerek', 'B', 9, 'Trening typu cardio skupia się na czynności:'),
       (10, 'Harry Potter i komnata tajemnic', 'Harry Potter i kamień filozoficzny', 'Harry Potter i czarna magia',
        'Harry Potter i więzień Azkabanu', 'C', 10,
        'Który z tych tytułów NIE należy do serii powieści o Harrym Potterze?'),
       (11, 'Meksyk', 'Japonia', 'Stany Zjednoczone', 'Ukraina', 'C', 11,
        'Które państwo obchodzi 4 lipca Dzień Niepodległości?'),
       (12, 'Medycyna', 'Fizyka', 'Botanika', 'Psychologia', 'B', 12,
        'W której dziedzinie nauki występuje teoria strun?'),
       (18, '60', '69', '71', '73', 'C', 5, 'Ile lat ma Jarosław Kaczyński?'),
       (19, '1910', '1915', '1918', '1920', 'C', 1, 'W którym roku Polska odzyskała niepodległość?'),
       (20, 'Jarosław Kaczyński', 'Jacek Kurski', 'Rafał Trzaskowski', 'Andrzej Duda', 'D', 1,
        'Kto w 2020 roku wygrał w Polsce wybory prezydenckie?'),
       (21, 'ma i przednie, i tylne', 'zastąpił rubla', 'zakrywa całe ciało', 'jest samotnikiem', 'B', 12,
        'Manat karaibski, tak jak afrykański, z kończyn ma tylko przednie. A manat azerbejdżański, tak jak turkmeński:');